apiVersion: v1
kind: Service
metadata:
  name: happytoys-backend-service
spec:
  selector:
    app: happytoys-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # Para que puedas acceder desde tu máquina
